FILE_NAME = '/home/ivan/Code/kargat/src/kargat/dep.yaml'
ROOT = "kargat"
ENVIRONMENT = "env"
ENVIRONMENT_FILE = "env_file"
REQUIREMENTS = "requiremnts"
DEV = "dev"
PROD = "prod"
TEST = "test"
COMMAND = "command"
COMMAND_LINK = "before"
COMMAND_DEFAULT = "start"
COMMAND_CMD = "cmd"
PYTHONUNBUFFERED="PYTHONUNBUFFERED=1"
NAME = "name"
VERSION = "version"
AUTHOR = "author"
